# language: sh
#
# before_script:
#   # - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-5_amd64.deb"
#   # - sudo dpkg -i "shellcheck_0.3.7-5_amd64.deb"
#   - sudo apt-get install shellcheck
#
# script:
#   - shellcheck make_it_awesome.sh
#   - shellcheck make_symlinks.sh
language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 # - bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'
 - shellcheck make_it_awesome.sh
 - shellcheck make_symlinks.sh

matrix:
  fast_finish: true

notifications:
  email: false

branches:
  only:
    - master
