language: sh

before_script:
  # - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-5_amd64.deb"
  # - sudo dpkg -i "shellcheck_0.3.7-5_amd64.deb"
  - sudo apt-get install shellcheck

script:
  - shellcheck make_it_awesome.sh
  - shellcheck make_symlinks.sh

notifications:
  email: false

branches:
  only:
    - master
