language: sh

sudo: required
dist: trusty

before_install:
  - sudo apt-get install shellcheck

script:

   - shellcheck make_it_awesome.sh
   - shellcheck make_symlinks.sh

matrix:
  fast_finish: true

notifications:
  email: false

branches:
  only:
    - master
