language: objective-c

notifications:
  email: false

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

env:
  - APM_TEST_PACKAGES="minimap"

git:
  depth: 10

branches:
  only:
    - master
